name: Docker Build & Push

on:
  push:
    branches:
      - productcatalogservice  # or change to your deployment branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t sikanderali/productcatalogservice:latest .

      - name: Push Docker Image
        run: |
          docker push sikanderali/productcatalogservice:latest
